apiVersion: apps/v1
kind: Deployment
metadata:
  name: lapzone-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: lapzone
  template:
    metadata:
      labels:
        app: lapzone
    spec:
      containers:
      - name: lapzone-container
        image: didin8080/lapzone
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: lapzone-service
spec:
  type: LoadBalancer
  selector:
    app: lapzone
  ports:
  - port: 80
    targetPort: 3000
