---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lapzone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lapzone
  template:
    metadata:
      labels:
        app: lapzone
    spec:
     containers:
       - name: django
         image: didin8080/lapzone:latest
         ports:
           - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: lapzone-service
spec:
  type: LoadBalancer
  selector:
    app: lapzone
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
