apiVersion: apps/v1
kind: Deployment
metadata:
  name: lapzone-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: lapzone
  template:
    metadata:
      labels:
        app: lapzone
    spec:
      containers:
      - name: lapzone-container
        image: didin8080/lapzone
        ports:
        - containerPort: 8000
